### ISSUE TITLE
Error: stream.push() after EOF

### ISSUE THREAD

**Issue by jotto** [LaurentZuijdwijk/streaming-cache#16]
## Explanation

I'm intermittently getting these `stream.push` errors on an HTTP server, which seem to terminate the Node process, even with a `process.on("unhandledRejection")`. I assume the error is happening because the HTTP client is disconnecting before the stream finishes, but why can't I seem to capture these errors and/or prevent Node from terminating?

## Possible solution?

Could it be as simple as adding try/catch around the `.push` call in readStream?https://github.com/LaurentZuijdwijk/streaming-cache/blob/90121ff3a405a8296a9eaa801e85af8a0a49d686/lib/readStream.js#L40

## Error message/stack

Note, the line numbers in this stack trace are a little off because I'm using the forked code from https://github.com/LaurentZuijdwijk/streaming-cache/pull/14

```
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:240:30)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at ReadStream._push (/app/node_modules/streaming-cache/lib/readStream.js:44:14)
    at ReadStream.setBuffer (/app/node_modules/streaming-cache/lib/readStream.js:19:10)
    at EventEmitter.<anonymous> (/app/node_modules/streaming-cache/index.js:105:16)
    at emitOne (events.js:116:13)
    at EventEmitter.emit (events.js:211:7)
    at Duplex.<anonymous> (/app/node_modules/streaming-cache/index.js:204:28)
    at emitNone (events.js:111:20)
    at Duplex.emit (events.js:208:7)
    at finishMaybe (_stream_writable.js:614:14)
    at endWritable (_stream_writable.js:622:3)
    at Duplex.Writable.end (_stream_writable.js:573:5)
    at ReadStream.onend (_stream_readable.js:595:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at ReadStream.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

## Code looks like:

```javascript
app.get('/', (req, res) => {
  const streamingCached = streamingCache.get("some-cache-key");

  if (streamingCached) {
    return streamingCached
      .pipe(res)
      .on("error", console.error)
  }
})
```

**Comment by jotto** [comment]
I deployed the try/catch and it seems to have addressed the problem: https://github.com/jotto/streaming-cache/commit/aa9f63c27889d6cbcb62f46d627fc11de110bb6e

**Comment by LaurentZuijdwijk** [comment]
@jotto, thanks for your work on this and sorry for the late reply. 
It seems like this issue is similar https://github.com/jeffbski/redis-rstream/issues/4 and their solution was to use a try/catch. There might be a small performance price to pay, but it shouldn't be too bad. 

I would suggest using 'uncaughtException' in your code. 'unhandledRejection' is only used for promises. 

The following might help as well. Errors are not automatically forwarded in a stream.

```
  if (streamingCached) {
    streamingCached    
     .on("error", console.error)
     return streamingCached
      .pipe(res)
      .on("error", console.error)
  }
```

**Comment by LaurentZuijdwijk** [comment]
Will close this issue. A new version has been pushed to NPM.
